# Generated by Django 4.1.13 on 2024-03-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookgenre',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='bookgenre',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='clothingitemstyle',
            old_name='clothingitem_id',
            new_name='clothingitem',
        ),
        migrations.RenameField(
            model_name='clothingitemstyle',
            old_name='style_id',
            new_name='style',
        ),
    ]
