# Generated by Django 4.1.13 on 2024-03-08 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_publisher_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'manufacturers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MobileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'mobile_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'styles',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.product')),
                ('release_date', models.DateField()),
                ('rom_size', models.IntegerField()),
                ('ram_size', models.IntegerField()),
                ('display_resolution', models.CharField(max_length=50)),
                ('battery_capacity', models.IntegerField()),
                ('chip', models.CharField(max_length=50)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobiles', to='product.manufacturer')),
                ('mobile_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobiles', to='product.mobiletype')),
            ],
            options={
                'db_table': 'mobiles',
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.product')),
                ('manufacturer_date', models.DateField()),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_items', to='product.manufacturer')),
                ('styles', models.ManyToManyField(to='product.style')),
            ],
            options={
                'db_table': 'clothes',
                'ordering': ['product__name'],
            },
        ),
    ]
