# Generated by Django 4.0.1 on 2024-03-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_book_id_bookgenre_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(through='product.BookGenre', to='product.Genre'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='styles',
            field=models.ManyToManyField(through='product.ClothingItemStyle', to='product.Style'),
        ),
    ]
