# Generated by Django 4.1.13 on 2024-03-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cart_id', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1)),
                ('product_id', models.IntegerField()),
            ],
            options={
                'db_table': 'cart_items',
                'ordering': ['-date_added'],
            },
        ),
    ]
