# Generated by Django 4.0.1 on 2024-03-24 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('C', 'Canceled'), ('A', 'Arrived'), ('T', 'Transporting'), ('H', 'Hold')], max_length=1)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_timestamp'],
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='0123456789', max_length=10),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.order')),
                ('method', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Visa', 'Visa'), ('Mastercard', 'Mastercard'), ('Cash on Delivery', 'Cash on Delivery')], max_length=30)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refunded', 'Refunded'), ('Canceled', 'Canceled'), ('Partially Paid', 'Partially Paid'), ('Expired', 'Expired')], max_length=50)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('expired_date', models.DateField(blank=True, null=True)),
                ('security_code', models.CharField(blank=True, max_length=6, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('debt_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.order')),
                ('shipping_address', models.TextField()),
                ('shipping_method', models.CharField(choices=[('Standard', 'Standard Shipping'), ('Air', 'Air Freight'), ('Sea', 'Sea Freight'), ('Express', 'Express Shipping'), ('Truck', 'Truck Delivery'), ('Mail', 'Mail Delivery'), ('Local', 'Local Delivery')], max_length=30)),
                ('estimated_delivery_date', models.DateField()),
                ('tracking_information', models.TextField(max_length=255)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'db_table': 'shipments',
                'ordering': ['-created_timestamp'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='user.user'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='user.order'),
        ),
    ]
