# Generated by Django 4.0.1 on 2024-03-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_order_cartitem_is_active_user_phone_number_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Arrived', 'Arrived'), ('Transporting', 'Transporting'), ('Hold', 'Hold')], max_length=30),
        ),
    ]
